### ISSUE TITLE
xml内设置的属性都木有起作用？

### ISSUE THREAD

**Issue by merbng** [xujianhui404/WeiboLine#2]
<xu.viewpagerflextitle.ViewPagerTitle
            android:id="@+id/pager_title"
            ViewPagerTitle:background_content_color="@android:color/white"
            ViewPagerTitle:line_start_color="@color/color_mine_text"
            ViewPagerTitle:line_end_color="@color/color_mine_text"
            ViewPagerTitle:selectedTextViewColor="@color/color_mine_text"
            ViewPagerTitle:defaultTextViewColor="@color/color_B3C5C5C5"
            ViewPagerTitle:item_margins="30dp"
            ViewPagerTitle:defaultTextViewSize="18dp"
            ViewPagerTitle:selectedTextViewSize="18dp"
            ViewPagerTitle:line_height="1dp"
            android:layout_width="match_parent"
            android:layout_height="44dp"/>
是我的使用方式有问题吗？
android:layout_height这个高度设置也无效。

**Comment by kaina404** [comment]
这个问题我下班后回去看看

**Comment by kaina404** [comment]
目前而言 如果设置无效  你可以重写他的onMeasure方法
