### ISSUE TITLE
用滑动控件包裹会不显示viewpage和横向的指示器，求大神解答

### ISSUE THREAD

**Issue by PangHaHa12138** [xujianhui404/WeiboLine#3]
布局如下：
<?xml version="1.0" encoding="utf-8"?>
<android.support.v4.widget.NestedScrollView
    xmlns:ViewPagerTitle="http://schemas.android.com/tools"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

<LinearLayout
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_height="match_parent">

<ImageView
            android:src="@drawable/meinv2"
            android:scaleType="fitXY"
            android:layout_width="match_parent"
            android:layout_height="200dp" />

        <xu.viewpagerflextitle.ViewPagerTitle
            android:id="@+id/pager_title"
            ViewPagerTitle:background_content_color="@android:color/white"
            ViewPagerTitle:line_start_color="@android:color/holo_red_dark"
            ViewPagerTitle:line_end_color="@android:color/white"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"/>

        <android.support.v4.view.ViewPager
            android:id="@+id/view_pager"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1">

        </android.support.v4.view.ViewPager>

</LinearLayout>
</android.support.v4.widget.NestedScrollView>

viewpage里面是recycleview
部分代码：
 public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {

        view = inflater.inflate(R.layout.fragment1,container,false);

//        smartRefreshLayout = (SmartRefreshLayout) view.findViewById(R.id.smartrefreshlayout);

        viewPagerTitle = (ViewPagerTitle) view.findViewById(R.id.pager_title);

        pager = (ViewPager) view.findViewById(R.id.view_pager);

        viewPagerTitle.initData(new String[]{"动态","头条"},pager,0);

        view1 = View.inflate(getActivity(),R.layout.view1,null);
        recyclerView1 = (RecyclerView) view1.findViewById(R.id.dongtailist);
        view2 = View.inflate(getActivity(),R.layout.view2,null);
        recyclerView2 = (RecyclerView) view2.findViewById(R.id.toutiao);

        listdata.add(new Testmodel());
        listdata.add(new Testmodel());
        listdata.add(new Testmodel());
        listdata.add(new Testmodel());
        listdata.add(new Testmodel());
        listdata.add(new Testmodel());
        listdata.add(new Testmodel());
        listdata.add(new Testmodel());
        listdata.add(new Testmodel());
        listdata.add(new Testmodel());

        LinearLayoutManager layoutManager = new LinearLayoutManager(getActivity());
        TestAdapter adapter = new TestAdapter(getActivity(),listdata);
        LinearLayoutManager layoutManager2 = new LinearLayoutManager(getActivity());

        views = new ArrayList<>();
        views.add(view1);
        views.add(view2);
        pagerAdapter = new MyPagerAdapter(views);
        pager.setAdapter(pagerAdapter);

        recyclerView1.setLayoutManager(layoutManager);
        recyclerView1.setAdapter(adapter);

        recyclerView2.setLayoutManager(layoutManager2);
        recyclerView2.setAdapter(adapter);

**Comment by kaina404** [comment]
简单看了下应该跟你的NestedScrollView有关系，具体问题我再分析下。

**Comment by PangHaHa12138** [comment]
我已经解决了，是我布局有问题，您的控件很好用

**Comment by kaina404** [comment]
android:fillViewport="true"添加这个属性就好了

**Comment by PangHaHa12138** [comment]
嗯 多谢 thanks for you help

**Comment by kaina404** [comment]
客气啦 你也可以
